apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-app
  name: fronend-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    service: frontend-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend-app
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-app
  template:
    metadata:
      labels:
        service: frontend-app
    spec:
      containers:
      - image: sumitkumarsingh/frontend-app:latest
        name: fronend-app
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always