apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_connections"
  DB_NAME: "connections"
  DB_HOST: "postgres-connections"
  DB_PORT: "5432"
  KAFKA_URL: kafka-sumitsvc:9092
  KAFKA_TOPIC: location
metadata:
  name: configmap-location-consumer